Hw 01
ivankrut856/Java-SPbAU pull request #1
Opened 2019-01-19 19:31 UTC by ivankrut856

2019-01-21 15:40 UTC, jzuken requested changes

2019-01-21 15:40 UTC, jzuken commented on hashTable/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
этот файл тоже не надо выкладывать, это настройки редактора

2019-01-21 15:40 UTC, jzuken commented on hashTable/src/main/java/fr/ladybug/team/hashTable/MapEntry.java
> +public class MapEntry {
этот класс никому за пределами таблицы и списка не нужен, лучше его спрятать. особенно если это дата-класс с публичными полями
ну и доков к нему не хватает

2019-01-21 15:40 UTC, jzuken commented on hashTable/src/main/java/fr/ladybug/team/hashTable/List.java
> +        capacity = 2;
так лучше инициализировать сразу при объявлении

2019-01-21 15:40 UTC, jzuken commented on hashTable/src/main/java/fr/ladybug/team/hashTable/HashTable.java
> +    private int mod(int x, int y)
сначала лучше всё же помещать поля, а потом уже методы

2019-01-21 15:40 UTC, jzuken commented on hashTable/src/main/java/fr/ladybug/team/hashTable/HashTable.java
> +    private int mod(int x, int y)
ну и нет причин ей не быть статической

2019-01-21 15:40 UTC, jzuken commented on hashTable/src/main/java/fr/ladybug/team/hashTable/HashTable.java
> +    private final int initialSpace = 2;
константы по соглашению именуются капсом

2019-01-21 15:40 UTC, jzuken commented on hashTable/src/main/java/fr/ladybug/team/hashTable/HashTable.java
> +        MapEntry[][] elems = new MapEntry[lists.length][];
там, где тип очевиден из правой части, лучше использовать var

2019-01-21 15:40 UTC, jzuken commented on hashTable/src/main/java/fr/ladybug/team/hashTable/HashTable.java
> +            elems[i] = lists[i].getData();
а можно было просто переложить всё новый массив, а потом присвоить его в lists. и не создавать ещё elems зачем-то

2019-01-21 15:40 UTC, jzuken commented on hashTable/src/main/java/fr/ladybug/team/hashTable/HashTable.java
> +    private int size;
все поля лучше группировать в одном месте в начале класса

2019-01-21 15:40 UTC, jzuken commented on hashTable/src/main/java/fr/ladybug/team/hashTable/HashTable.java
> +        int pos = mod(key.hashCode(), lists.length);
не надо экономить на именах, читаемость программы важнее

2019-01-21 15:40 UTC, jzuken commented on hashTable/src/main/java/fr/ladybug/team/hashTable/HashTable.java
> +        if (res == null) {
ну вообще-то туда могли сознательно положить null как значение

2019-01-21 15:40 UTC, jzuken commented on hashTable/src/main/java/fr/ladybug/team/hashTable/HashTable.java
> +        for (int i = 0; i < lists.length; i++) {
ну то есть у вас получается расширяющаяся и никогда не уменьшающаяся таблица

2019-01-21 15:40 UTC, jzuken commented on hashTable/src/test/java/fr/ladybug/team/hashTable/HashTableTest.java
> +        HashTable table = new HashTable();
а ещё можно использовать @BeforeEach для инициализации хеш-таблицы и не копипастить одно и то же

2019-01-21 19:19 UTC, ivankrut856 commented on hashTable/src/main/java/fr/ladybug/team/hashTable/HashTable.java
> +        for (int i = 0; i < lists.length; i++) {
Ну да, мне кажется, что это общий подход такой. Какой-нибудь vector тоже не уменьшается

2019-01-21 19:35 UTC, ivankrut856 commented on hashTable/src/main/java/fr/ladybug/team/hashTable/HashTable.java
> +            elems[i] = lists[i].getData();
Мне кажется, что так лучше. Смотрите. Мне нужно будет временное хранилище anyway. У меня это elems. Но у меня есть функция put, которая классно кладёт элемент в lists, если бы я сделал какой-нибудь newLists, который потом захочу присвоить lists = newLists, мне нужен был бы код put, но уже для newLists. А в чём плюсы тогда?

2019-01-22 11:54 UTC, jzuken commented on hashTable/src/main/java/fr/ladybug/team/hashTable/HashTable.java
> +        for (int i = 0; i < lists.length; i++) {
ну, у вектора есть resize() и shrink_to_fit(), которых у вас нет. то есть вашу таблицу вообще никак не сделать меньше, что фигово. пусть хотя бы clear() возвращает её к исходному состоянию

2019-01-22 11:55 UTC, jzuken commented on hashTable/src/main/java/fr/ladybug/team/hashTable/HashTable.java
> +            elems[i] = lists[i].getData();
что мешает просто сохранить старый массив куда-то и добавлять тем же put-ом в новый? я против бессмысленного создания и копирования элементов

2019-01-22 12:52 UTC, ivankrut856 commented on hashTable/src/main/java/fr/ladybug/team/hashTable/HashTable.java
> +            elems[i] = lists[i].getData();
Хм. Норм. Не додумался

2019-02-27 14:13 UTC, merged