The thing is firing now!
ivankrut856/Java-SPbAU pull request #11
Opened 2019-05-19 20:39 UTC by ivankrut856

2019-05-20 15:45 UTC, ivankrut856 commented
Please note that controls are not standart. Use "question mark" button to get help

2019-05-31 11:59 UTC, RamSaw commented
назовите PR по нормальному то...

2019-05-31 12:14 UTC, ivankrut856 commented
> назовите PR по нормальному то...

Done

2019-05-31 13:13 UTC, RamSaw requested changes
@ivankrut856 проверил, жду исправлений или контраргументов. Позовите меня, как исправите через собаку.

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/build.gradle
> +mainClassName = 'fr.ladybug.team.Screen'
jar не запускается

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/settings.gradle
> +rootProject.name = 'scorchedEarth'
танк круто нарисован :)
еще в процессе игры, мой терминал заполонился этими сообщениями:
GL: 1
47
GL: 1
47
GL: 1
47
GL: 1
47
мне кажется этого не должно быть.

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/Screen.java
> +            model.getTank().setDeltaX(-1);
давайте выделим это в константы, и они всегда пожалуй должны быть одинаковы и константа нам в этом поможет, не наплодить баги.

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/Screen.java
> +
2 пустых строчки перебор

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Cell.java
> +        getView().chooseTexture(presenceStatus.value);
мне кажется здесь лучше использовать view просто. getView как-то смущает, будто это будет другой view какой-то. Вот в других методах кроме конструктора это уже разумно делать.

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Cell.java
> +        // Sorry, but empty
sorry?

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/FieldMap.java
> +    public static boolean getState(int i, int j) {
давайте State сделаем enum'ом

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Model.java
> +        tank = new Tank(0, CELL_ROWS_COUNT - 8, tankBody, tankGun, this);
правильно ли я понимаю, что -8 очень сильно зависит от карты? Которая еще подгружается как внешний файл. Давайте в коде просто вычислим, а какой у танка Y должен быть.

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Model.java
> +        var tankGun = new TankGunView(new Rectangle(5, 12), tankGunTextures);
всякие размеры я бы тоже в константы вынес и как-нибудь сгруппировал, чтобы потом было легко изменить размера танка. А то так придется вчитываться в код и разбираться, что за что отвечает.

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Model.java
> +            min = Math.min(min, y - tank.getY() - 2);
-2, +100, +5. Не понимаю, что это за константы. Мне кажется, если дать им имя, сразу станет понятно, что делает метод и почему делает это именно так.

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Model.java
> +            if (rectangle.contains(centerOfRectangle(cell.getView().getRectangle()))) {
а это что за случай такой? я смог только выйти за пределы поля и танк умер, но это кажется случай, когда я каким-то образом заехал в землю. Это как воспроизвести?

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Projectile.java
> +            throw new RuntimeException("WTF");
плохое сообщение об ошибке

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Projectile.java
> +        return Math.toDegrees(-mathAngle + Math.PI/2);
пробелы

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Projectile.java
> +        return Math.toDegrees(-mathAngle + Math.PI/2);
мб не mathAngle, а radians?

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Tank.java
> +        System.out.println("GL: " + groundLevel);
ах вот оно что. А зачем это?

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Tank.java
> +        if (-1 <= groundLevel && groundLevel <= 0 /* should go up */) {
плохо так писать комменты. пишите уж тогда после {

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Tank.java
> +        if (currentGame.checkTankCrush(this)) {
а понял. это типа чтобы не залезать в землю просто. Напишите тогда зачем это нужно в джавадоке. Потому что кажется, что после crush нужно умирать или что-то подобноею

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Tank.java
> +                x + 2.4, y,
2.4 тоже странная константа

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Tank.java
> +            y += groundLevel - 1;
иногда это может быть -2, а не -1, так и задумывалось?

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Target.java
> +    public Target(Cell myCell, TargetView view) {
myCell ни о чем не говорящее название.

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/views/CellView.java
> +        chooseTexture(0);
DEFAULT_TEXTURE

2019-05-31 13:13 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/views/TargetView.java
> +        System.out.println(texture.getImage());
это зачем?

2019-05-31 13:54 UTC, ivankrut856 commented on scorchedEarth/settings.gradle
> +rootProject.name = 'scorchedEarth'
Осталось от дебага, убрал

2019-05-31 13:54 UTC, ivankrut856 commented on scorchedEarth/src/main/java/fr/ladybug/team/Screen.java
> +            model.getTank().setDeltaX(-1);
Done

2019-05-31 13:56 UTC, ivankrut856 commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Cell.java
> +        // Sorry, but empty
> 
>         // Empty at this point of development
>         // Can be useful in the future

2019-05-31 14:13 UTC, ivankrut856 commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Model.java
> +            if (rectangle.contains(centerOfRectangle(cell.getView().getRectangle()))) {
Так не может забираться больше, чем на 2 клетки в высоту, после осознания, что танк въехал в землю и не забрался (потому что высоко) происходит отказ в движении, то есть танк делает вид, что даже не пытался туда ехать

2019-05-31 14:15 UTC, ivankrut856 commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Projectile.java
> +        return Math.toDegrees(-mathAngle + Math.PI/2);
> пробелы

Ходят слухи, что можно групировать операции для улучшения читаемости



> мб не mathAngle, а radians?

У меня есть два угла. Один из них математический (нормальный), а другой "поворотный", поэтому такие названия, а не из-за градусов или радианов

2019-05-31 14:16 UTC, ivankrut856 commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Tank.java
> +        System.out.println("GL: " + groundLevel);
Остатки дебага, удаляю

2019-05-31 14:18 UTC, ivankrut856 commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Tank.java
> +            y += groundLevel - 1;
Да, танк не залезает больше, чем на 2 блока

2019-05-31 14:21 UTC, ivankrut856 commented on scorchedEarth/src/main/java/fr/ladybug/team/views/TargetView.java
> +        System.out.println(texture.getImage());
Остатки дебага, удаляю

2019-05-31 14:22 UTC, ivankrut856 commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Tank.java
> +        if (currentGame.checkTankCrush(this)) {
Мб лучше назвать адекватнее. checkTankCollision?

2019-05-31 14:48 UTC, ivankrut856 commented
@RamSaw requested changes performed

2019-05-31 14:49 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Projectile.java
> +        return Math.toDegrees(-mathAngle + Math.PI/2);
стайлгайду такое отсутствие пробелов точно противоречит. У Вас выражение то короткое, куда читаемость денется от 2 пробелов? Мне лично это ухудшает читаемость, потому что я уже привык видеть всегда пробелы между знаками арифметическими

ок, а что значит математический нормальный?

2019-05-31 14:49 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Tank.java
> +        if (currentGame.checkTankCrush(this)) {
тоже можно

2019-05-31 14:52 UTC, ivankrut856 commented on scorchedEarth/src/main/java/fr/ladybug/team/models/Projectile.java
> +        return Math.toDegrees(-mathAngle + Math.PI/2);
Ладно, ща

У математического 0 у вектора (1, 0), 90 у (0, 1) и так далее. Это нормально. А у меня ещё есть другой угол, которые является углом поворота пушки. Там 0 в изначальном состоянии, которое 90 в нормальном мире. А ещё угол пушки увеличивается в другом направлении

2019-05-31 14:54 UTC, ivankrut856 commented
@RamSaw поставил таки пробелы

2019-05-31 14:56 UTC, RamSaw requested changes
@ivankrut856
jar по прежнему не запускается

2019-05-31 14:56 UTC, RamSaw commented on scorchedEarth/src/main/java/fr/ladybug/team/FieldMap.java
> +//    }
:(
удалите уж

2019-05-31 14:57 UTC, ivankrut856 commented
> @ivankrut856
> jar по прежнему не запускается

А что за jar? Я так не понял

2019-05-31 15:03 UTC, ivankrut856 commented
> @ivankrut856
> jar по прежнему не запускается

@RamSaw подскажите, где вы берёте jar, и каким образом он должен запускаться

2019-05-31 15:35 UTC, RamSaw commented
> > @ivankrut856
> > jar по прежнему не запускается
> 
> @RamSaw подскажите, где вы берёте jar, и каким образом он должен запускаться

вы выполняете ./gradlew build и у вас собирается jar файл, грубо говоря бинарник, только чтобы его запустить нужна еще JVM.
запускается так:
java -jar ./build/libs/<name-of-jar>.jar

2019-05-31 15:53 UTC, ivankrut856 commented
> > > @ivankrut856
> > > jar по прежнему не запускается
> > 
> > 
> > @RamSaw подскажите, где вы берёте jar, и каким образом он должен запускаться
> 
> вы выполняете ./gradlew build и у вас собирается jar файл, грубо говоря бинарник, только чтобы его запустить нужна еще JVM.
> запускается так:
> java -jar ./build/libs/.jar

@RamSaw 
Раньше нас не просили добавлять поддержку сборки jar, потому что штука нормально запускается просто через ./gradlew run.
Добавил в build.gradle эту поддержку. Другое дело, что запускать нужно всё равно не так просто, а через java --module-path $PATH_TO_FX --add-modules javafx.controls -jar build/libs/.jar, поэтому проще через ./gradlew run энивей

2019-06-04 11:43 UTC, RamSaw commented
@ivankrut856 все ок.
@jzuken

2019-06-06 07:47 UTC, merged