MyJUnit
ivankrut856/Java-SPbAU pull request #13
Opened 2019-06-01 18:25 UTC by ivankrut856

2019-06-07 17:29 UTC, jzuken requested changes

2019-06-07 17:29 UTC, jzuken commented on myjunit/src/test/java/fr/ladybug/team/TesterTest.java
> +        assertEquals(Tester.TestResult.TestResultState.SUCCESS, results.get(0).getState());
fr.ladybug.team.TesterTest > testComplexTest() FAILED
    org.opentest4j.AssertionFailedError at TesterTest.java:88
-1

2019-06-07 17:29 UTC, jzuken commented on myjunit/src/main/java/fr/ladybug/team/annotations/Test.java
> +    Class<?>[] expected() default {};
доки?
-1

2019-06-07 17:29 UTC, jzuken commented on myjunit/src/main/java/fr/ladybug/team/Tester.java
> +    private void Tester() {
конструктор, который возвращает void?

2019-06-07 17:29 UTC, jzuken commented on myjunit/src/main/java/fr/ladybug/team/Tester.java
> +            if (method.isAnnotationPresent(Test.class)) {
а ещё хорошо бы проверить, что аннотаций не больше одной
-0.5

2019-06-07 17:29 UTC, jzuken commented on myjunit/src/main/java/fr/ladybug/team/Tester.java
> +                throw new RuntimeException("@BeforeClass invocation error. Shouldn't normally happen");
что, JUnit тоже исключения кидает, когда что-то идёт не так?

2019-06-09 16:56 UTC, ivankrut856 commented on myjunit/src/main/java/fr/ladybug/team/Tester.java
> +            if (method.isAnnotationPresent(Test.class)) {
Зачем? У меня штука позволяет быть одновременно и тестом и before и всем, чем угодно, это удобно. Почему так не должно быть?

2019-06-09 17:07 UTC, ivankrut856 commented on myjunit/src/test/java/fr/ladybug/team/TesterTest.java
> +        assertEquals(Tester.TestResult.TestResultState.SUCCESS, results.get(0).getState());
Странно. Ни у меня, ни на travis такого не происходит. Кажется, travis специально для спорных случаев вводился. Как это воссоздать вообще?

2019-06-09 17:08 UTC, ivankrut856 commented on myjunit/src/main/java/fr/ladybug/team/Tester.java
> +                throw new RuntimeException("@BeforeClass invocation error. Shouldn't normally happen");
Это "не так" -- внутренняя ошибка, которая никогда-никогда-никогда не должна происходить. Хорошо, теперь там сообщение об ошибке и пропуске

2019-06-10 07:56 UTC, jzuken commented on myjunit/src/main/java/fr/ladybug/team/Tester.java
> +            if (method.isAnnotationPresent(Test.class)) {
BeforeAll, например, требует статического метода, а Test нет

2019-06-10 08:12 UTC, jzuken commented on myjunit/src/test/java/fr/ladybug/team/TesterTest.java
> +        assertEquals(Tester.TestResult.TestResultState.SUCCESS, results.get(0).getState());
хех, ну вот такие у вас тесты, что они падают, а вы не можете по их выводу понять почему. могу подсказать, что первым запускается simpleFail(), который ожидаемо падает

2019-06-10 09:16 UTC, ivankrut856 commented on myjunit/src/main/java/fr/ladybug/team/Tester.java
> +            if (method.isAnnotationPresent(Test.class)) {
У меня не требовало) Хорошо, я переделал. Также добавил эти требования в документацию

2019-06-10 09:17 UTC, ivankrut856 commented on myjunit/src/test/java/fr/ladybug/team/TesterTest.java
> +        assertEquals(Tester.TestResult.TestResultState.SUCCESS, results.get(0).getState());
Методы могут идти в произвольном порядке, блин :( Добавил сортировку по имени, теперь должно быть нормально

2019-06-12 10:03 UTC, jzuken requested changes

2019-06-12 10:03 UTC, jzuken commented on myjunit/src/main/java/fr/ladybug/team/annotations/Test.java
> +    Class<?>[] expected() default {};
ну доков к методам так и не появилось :(
-1

2019-06-13 12:05 UTC, merged