Myftp
ivankrut856/Java-SPbAU pull request #14
Opened 2019-06-05 02:45 UTC by ivankrut856

2019-06-09 13:45 UTC, RamSaw requested changes
@ivankrut856 проверил. Вы правда кажется эту ветку создали от дз про Cannon, поэтому cannon и сюда добавился. Но не страшно.
-1 за то, что я так и не смог запустить вашего клиента :(
+1 за хорошие тесты.

2019-06-09 13:45 UTC, RamSaw commented on myftp/build.gradle
> +mainClassName = 'fr.ladybug.team.ClientInterface'
нет таски для сервера, как итоге невозможно запустить его

2019-06-09 13:45 UTC, RamSaw commented on myftp/build.gradle
> +mainClassName = 'fr.ladybug.team.ClientInterface'
да и клиент тоже:
./gradlew run

Task :run FAILED
Error: Could not find or load main class fr.ladybug.team.ClientInterface
Caused by: java.lang.ClassNotFoundException: fr.ladybug.team.ClientInterface

FAILURE: Build failed with an exception.

2019-06-09 13:45 UTC, RamSaw commented on myftp/build.gradle
> +mainClassName = 'fr.ladybug.team.ClientInterface'
при запуске клиента в IDEA получаю следующее:
Jun 09, 2019 4:00:03 PM fr.ladybug.team.client.ClientInterface start
INFO: Starting the application.
Exception in Application start method
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalAccessError: superclass access check failed: class com.sun.javafx.scene.control.ControlHelper (in unnamed module @0x30796fdd) cannot access class com.sun.javafx.scene.layout.RegionHelper (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.scene.layout to unnamed module @0x30796fdd
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at javafx.scene.control.Control.<clinit>(Control.java:86)
	at javafx.scene.control.DialogPane.createContentLabel(DialogPane.java:167)
	at javafx.scene.control.DialogPane.<init>(DialogPane.java:218)
	at javafx.scene.control.Dialog.<init>(Dialog.java:512)
	at javafx.scene.control.TextInputDialog.<init>(TextInputDialog.java:76)
	at fr.ladybug.team.client.ClientInterface.start(ClientInterface.java:41)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 1 more

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/client/Client.java
> +        fileTree = new Stack<>();
интересное решение для дерева путей использовать стэк. А почему не просто Path.getParent()?

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/client/Client.java
> +        new Thread(task).start();
а зачем это в отдельном потоке делать?

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/client/Client.java
> +     * Saves the file with given filename in current working directory into current working folder in local machine.
не надо в current working. А если у меня есть файл такой и я хочу скачать его в другое место? Вы мне просто перетрете файл и потом восстановить будет практически невозможно

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/client/ClientInterface.java
> +            } catch (NumberFormatException ignore) { // will show "incorrect" alert.
сделайте show тогда уж

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/client/ResponseList.java
> +                String filename = new String(stream.readNBytes(stringSize));
как-то сложно. Проще же writeUTF, readUTF, writeBoolean, readBoolean.

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/client/ResponseList.java
> +        return Arrays.asList(fileViews);
не легче сразу листом сделать это поле?

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/server/Server.java
> +public class Server {
этот файл точно надо разбить на несколько, у меня даже diff не прогрузился.

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/server/Server.java
> +    private final @NotNull Selector acceptSelector;
почему вы выбрали селекторы?
мне кажется выбрав просто "блокирующая архитектура с потоком на каждого клиента" получилось бы гораздо меньше кода и его было бы легче разбить на сущности.

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/server/Server.java
> +            System.out.println("Require 2 arguments: the address and port number");
сделайте address по умолчанию какой-нибудь.
Вы кстати понимаете почему вам понадобился он?

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/server/Server.java
> +            server = new Server(address, portNumber);
добавьте в интерфейс лучше метод start.
это не очень очевидное и удобное с моей точки зрение поведение, что при создании объекта он сразу начинает работать в каком-то другом потоке.
выглядит так, будто вы его создали и потом благополучно забыли про него

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/client/ClientInterface.java
> +    public void start(Stage primaryStage) throws Exception {
IDEA говорит, что тут Exception вылететь не может

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/server/Server.java
> +                    var controller = (TransmissionController)key.attachment();
пробел

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/server/Server.java
> +                continue;
а смысл этого? если дальше потом все равно итерируемся, и если пусто, то просто не зайдем в цикл.

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/server/Server.java
> +            fileBytes = Files.readAllBytes(path);
может не влезть если файл большой

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/server/Server.java
> +            private final int defaultPackageSize = -5;
-5? Почему -5?

2019-06-09 13:45 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/server/Server.java
> +                    if (channel.read(byteBuffers) == -1) {
а что если считаются не все данные? надо же цикл где-то написать, без него никак.

2019-06-09 17:24 UTC, ivankrut856 commented on myftp/src/main/java/fr/ladybug/team/client/Client.java
> +        fileTree = new Stack<>();
Потому что у меня есть внутреннее состояние -- позиция в дереве fs. И положить/убрать на стэк -- гораздо проще, чем переприсваивать файл. Для этого нужно будет взять путь, отрезать всё до слэша или другого разделителя. А в стэк просто.

2019-06-09 17:24 UTC, crossopt commented on myftp/src/main/java/fr/ladybug/team/server/Server.java
> +    private final @NotNull Selector acceptSelector;
Эта домашка была продолжением задания с практики, на которой было явно указано, что нужно использовать неблокирующую архитектуру, поэтому в домашке тоже используется она.
Мы бы рады, так-то((

2019-06-09 17:28 UTC, ivankrut856 commented on myftp/src/main/java/fr/ladybug/team/client/ClientInterface.java
> +            } catch (NumberFormatException ignore) { // will show "incorrect" alert.
Ну так он дальше провалится в обработчик "incorrect format". Это удобно, потому что при исключении я делаю то же самое, что и при не выходе из цикла while. Единственный способ не попасть на него -- сделать всё правильно и выйти через break, либо упасть с другим исключением, которое другой кусок кода обработает

2019-06-09 17:29 UTC, ivankrut856 commented on myftp/src/main/java/fr/ladybug/team/client/ResponseList.java
> +                String filename = new String(stream.readNBytes(stringSize));
Извините, но моё решение гораздо лучше, потому что не зависит от кодировки. В функции кодировки/раскодировки можно подставить любую кодировку и будет норм. А встроенные writeUTF пишут в UTF-8 всегда :( Я бы и рад пользоваться стандартными, если бы они не были такими узкими в использовании

2019-06-09 17:31 UTC, ivankrut856 commented on myftp/src/main/java/fr/ladybug/team/client/ResponseList.java
> +        return Arrays.asList(fileViews);
Да)

2019-06-09 17:32 UTC, ivankrut856 commented on myftp/src/main/java/fr/ladybug/team/client/ClientInterface.java
> +    public void start(Stage primaryStage) throws Exception {
Да)

2019-06-09 17:35 UTC, ivankrut856 commented on myftp/src/main/java/fr/ladybug/team/client/Client.java
> +        new Thread(task).start();
Чтобы не блокировать интерфейс на это время. Когда я захожу в папку, до момента получения списка файлов отображается единственный псевдо-файл с названием LOADING :)

2019-06-09 18:18 UTC, crossopt commented on myftp/src/main/java/fr/ladybug/team/server/Server.java
> +            private final int defaultPackageSize = -5;
Отрицательная константа, которая точно не может посылаться как packageSize (он >= 0). Сделала -1, чтобы это было очевиднее, и дописала комментарий.

2019-06-09 18:41 UTC, ivankrut856 commented on myftp/src/main/java/fr/ladybug/team/client/Client.java
> +     * Saves the file with given filename in current working directory into current working folder in local machine.
Requested feature implemented :)

2019-06-09 19:16 UTC, ivankrut856 commented on myftp/src/main/java/fr/ladybug/team/server/Server.java
> +            System.out.println("Require 2 arguments: the address and port number");
Сделали по умолчанию localhost. Не понимаю, кто нам понадобился, о чём вы?)) Если вам интересно, почему мы даём выбирать адрес, то сервер может захотеть работать на любом адаптере, поэтому предоставляется выбор. Конкретно кейс был, что сначала мы тестили на одном компьютере, а потом в локальной сети роутера, например

2019-06-09 20:06 UTC, crossopt commented
@RamSaw все либо поправили, либо прокомментировали, почему не поправили.
Про запуск: в грэдле был косяк, да, сорри. Сейчас для обоих частей приложения создаются jar (при ./gradlew build), но ClientInterface (так как является JavaFX приложением) приходится запускать с указанием пути к JavaFX, поэтому сделали так, что при ./gradlew run запускается он.

2019-06-13 09:27 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/client/ResponseList.java
> +                String filename = new String(stream.readNBytes(stringSize));
Без знаний о кодировке передовать что-то по сети невозможно.
Вы используете такой конструктор:
String(byte[] bytes) 
Constructs a new String by decoding the specified array of bytes  using the platform's default charset.
Это наоборот потенциально может привести к ошибке, если у клиента и сервера будут разные дефолтные кодировки. Так что лучше хардкодить UTF-8 и не париться.

2019-06-13 09:37 UTC, RamSaw commented on myftp/build.gradle
> +    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
здесь надо указывать не compile, а runtime и тогда все будет работать без указаний пути к jar файлу.

2019-06-13 09:37 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/server/Server.java
> +            System.out.println("Require 2 arguments: the address and port number");
localhost наверное не самый лучший адрес по умолчанию, но да ладно.
Ваши сокурсники, к примеру, обращались к серверу гугла, который говорил им, какой у них IP.

2019-06-13 09:43 UTC, RamSaw requested changes
@ivankrut856 @crossopt 
в целом все норм. Только кодировку все же надо делать конкретную, поэтому замените использование конструктора String(bytes) на String(bytes, charset). Предлагаю UTF-8 использовать.
Я знаю, что у вас сегодня дедлайн. Но фиксить вроде совсем немного, так что я думаю вы успеете.

2019-06-13 09:43 UTC, RamSaw commented on myftp/src/main/java/fr/ladybug/team/server/TransmissionController.java
> +        private final int defaultPackageSize = -1; // a package size that сould not have been possibly sent.
джавадок лучше написать

2019-06-13 10:25 UTC, RamSaw commented
@ivankrut856 еще build.gradle compile на runtime замените

2019-06-13 10:43 UTC, RamSaw requested changes

2019-06-13 10:43 UTC, RamSaw commented on myftp/build.gradle
> +    from { configurations.runtime.collect { it.isDirectory() ? it : zipTree(it) } }
у вас это работает? Кажется там не runtime, а runtimeClasspath
Вот так:
 from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
 }

2019-06-13 10:46 UTC, ivankrut856 commented on myftp/build.gradle
> +    from { configurations.runtime.collect { it.isDirectory() ? it : zipTree(it) } }
У нас чёт ничего не работает из этого. Это всё JavaFX виноват. И то, что мы не умеем нормально делать jarники

2019-06-13 11:07 UTC, RamSaw commented on myftp/build.gradle
> +    from { configurations.runtime.collect { it.isDirectory() ? it : zipTree(it) } }
Хм, у кого-то я точно помню, что работало runtime. Ладно, раз прописав пути к JavaFX запустить можно, то норм.

2019-06-13 11:08 UTC, RamSaw approved these changes
@ivankrut856 @crossopt все ок
@jzuken

2019-06-13 12:46 UTC, merged