First version
ivankrut856/Java-SPbAU pull request #2
Opened 2019-01-28 21:48 UTC by ivankrut856

All functional is included.

2019-02-13 08:27 UTC, jzuken requested changes

2019-02-13 08:27 UTC, jzuken commented on trie/src/main/java/fr/ladybug/trie/Serializable.java
> +public interface Serializable {
а тут где документация? интерфейсы ещё даже более важно документировать хорошо
-0.5

2019-02-13 08:27 UTC, jzuken commented on trie/src/main/java/fr/ladybug/trie/Trie.java
> +        headNode = new TrieNode();
лучше инициализировать при объявлении сразу

2019-02-13 08:27 UTC, jzuken commented on trie/src/main/java/fr/ladybug/trie/Trie.java
> +            DataOutputStream stream = new DataOutputStream(out);
тут тоже можно var

2019-02-13 08:27 UTC, jzuken commented on trie/src/main/java/fr/ladybug/trie/Trie.java
> +            for (Map.Entry<Character, TrieNode> entry : links.entrySet()) {
и тут, и ещё много где. вот раз ради таких конструкций var и ввели
-0.5

2019-02-13 08:27 UTC, jzuken commented on trie/src/test/java/fr/ladybug/trie/TrieTest.java
> +
тесты на исключения? тесты на сериализацию?
-1

2019-02-13 08:27 UTC, jzuken commented on trie/src/main/java/fr/ladybug/trie/Trie.java
> +        private void deserializeFromDataStream(DataInputStream stream) throws IOException {
а если формат данных неправильный?

2019-02-16 20:34 UTC, ivankrut856 commented on trie/src/main/java/fr/ladybug/trie/Serializable.java
> +public interface Serializable {
За что снимаете баллы? В памятке не было никакой инфы про это... Забыл

2019-02-17 22:11 UTC, ivankrut856 commented on trie/src/main/java/fr/ladybug/trie/Trie.java
> +            for (Map.Entry<Character, TrieNode> entry : links.entrySet()) {
Вы же сказали, что только тогда, когда очевидно из правой части... Здесь в правой части ничего не сказано про типы. Нет, я конечно, поменяю, но какие-то нестабильные требования...

2019-02-17 22:38 UTC, ivankrut856 commented on trie/src/test/java/fr/ladybug/trie/TrieTest.java
> +
Блин, а за это тоже теперь снимают? В памятке не было написано же...

2019-03-07 11:44 UTC, jzuken requested changes

2019-03-07 11:44 UTC, jzuken commented on trie/src/main/java/fr/ladybug/trie/Serializable.java
> +/**
однострочные доки так лучше и писать одной строкой: `/** ... */`

2019-03-07 11:44 UTC, jzuken commented on trie/src/main/java/fr/ladybug/trie/Trie.java
> +    public Trie() {
а этот тут зачем?

2019-03-07 11:44 UTC, jzuken commented on trie/src/main/java/fr/ladybug/trie/Trie.java
> +    public boolean remove(String element) {
а если передадут null, то всё упадёт. и не только тут. аннотаций нет, никаких проверок тоже
-1

2019-03-07 11:44 UTC, jzuken commented on trie/src/test/java/fr/ladybug/trie/TrieTest.java
> +        assertDoesNotThrow(() -> dataExpected.writeInt(0));
а зачем тут эти проверки? это же не ваша функциональность

2019-03-13 14:08 UTC, jzuken commented
а сделайте, пожалуйста, конфиг тревиса, чтобы у вас не было конфликтов постоянно в мастере. например, чтобы оно в мастере проверяло все проекты сразу

2019-03-13 18:38 UTC, ivankrut856 commented
> а сделайте, пожалуйста, конфиг тревиса, чтобы у вас не было конфликтов постоянно в мастере. например, чтобы оно в мастере проверяло все проекты сразу

Специально посоветовался с ребятами, чтобы понять как лучше. Литвинов разрешает своей группе вносить небольшие изменения каждый раз, чтобы замёржить. У меня тогда будет компромисный вариант. Файлы не конфликтуют только если абсолютно одинаковые, поэтому у меня будет общий файл на все ветки, но тогда некоторые таски у CI будут падать (те, которые не про эту ветку). Я считаю, так можно жить

2019-03-13 19:30 UTC, jzuken commented
а можно сделать в мастере проверку всех веток сразу, и в каждой ветке только добавлять новую строчку в конфиг. тогда и конфликтов не будет

2019-03-13 19:56 UTC, ivankrut856 commented
> а можно сделать в мастере проверку всех веток сразу, и в каждой ветке только добавлять новую строчку в конфиг. тогда и конфликтов не будет

Сейчас ветка в том состоянии, как я понял ваше предложение. Конфликты всё равно присутствуют. Что делать?

2019-03-14 14:53 UTC, jzuken commented
добавлять не в середину списка, а в конец, как все делают?

2019-03-14 14:59 UTC, ivankrut856 commented
> добавлять не в середину списка, а в конец, как все делают?
Я не могу иметь в файле Трэвиса в ветке больше, чем одну задачу, потому что тест будет падать всё равно, поэтому найдётся ветка, у которой строчка не в конце списка в файле в мастере, в чём соль?

2019-03-14 15:45 UTC, ivankrut856 commented
> добавлять не в середину списка, а в конец, как все делают?

Так. Ща я попробую супер иновационный подход. Don't panic

2019-03-14 20:14 UTC, ivankrut856 commented
> добавлять не в середину списка, а в конец, как все делают?

Так. Я официально сделал универсальный конфиг. Теперь всё работат

2019-03-16 14:39 UTC, merged