Hw 03
ivankrut856/Java-SPbAU pull request #4
Opened 2019-02-11 13:01 UTC by ivankrut856

2019-02-28 09:56 UTC, jzuken requested changes

2019-02-28 09:56 UTC, jzuken commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +public class MyTreeSet<T> extends AbstractSet<T> {
> Необходимо реализовать интерфейс MyTreeSet с использованием бинарного дерева:

вы что-то другое сделали, явно просилось реализовать интерфейс
-0.5

2019-02-28 09:56 UTC, jzuken commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +    private Comparator<T> comparator = null;
тут явно чего-то не хватает у параметров-типов. внимательнее с генериками
-0.5

2019-02-28 09:56 UTC, jzuken commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +        private TreeNode left = null, right = null;
лучше не писать на одной строке

2019-02-28 09:56 UTC, jzuken commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +    private class TreeNode {
вложенные классы лучше убирать в конец объемлющего

2019-02-28 09:56 UTC, jzuken commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +    public @NotNull Iterator<T> descendingIterator() {
идея говорит, что этот метод нигде не используется. что как бы намекает, что тест на него вы не написали. да и на нормальный итератор там что-то странное написано
-1

2019-02-28 09:56 UTC, jzuken commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +        while (currentNode != null) {
этот код ровно такой же, как в ceiling(). а в lower() практически то же самое, что в floor(). не надо копировать код, выделяйте дополнительные функции
-1

2019-02-28 09:56 UTC, jzuken commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +    public boolean add(T element) {
аннотация?

2019-02-28 09:56 UTC, jzuken commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +        while (true) {
не надо так делать, вы ленитесь, чтобы нормально написать условие выхода из цикла, а потом код сложно понимать

2019-02-28 09:56 UTC, jzuken commented on myTreeSet/src/test/java/fr/ladybug/team/MyTreeSetTest.java
> +    MyTreeSet<String> basic, advanced;
поля в тестах -- не повоз забивать на модификаторы видимости. будьте аккуратнее
-0.5

2019-02-28 09:56 UTC, jzuken commented on myTreeSet/src/test/java/fr/ladybug/team/MyTreeSetTest.java
> +    void SetsInitialise() {
стайлгайл отменили?
-0.5

2019-02-28 09:56 UTC, jzuken commented on myTreeSet/src/test/java/fr/ladybug/team/MyTreeSetTest.java
> +class MyTreeSetTest {
тесты на исключения? на те же грабли наступаете, в третий раз больше баллов снимать буду
-1

2019-02-28 10:06 UTC, ivankrut856 commented on myTreeSet/src/test/java/fr/ladybug/team/MyTreeSetTest.java
> +class MyTreeSetTest {
Потому что это всё в одном и том же интервале проверки. Уверен, что у меня куча одинаковых ошибок во всех задачах, потому что сначала я все их написал, а сейчас вы все их проверяете

2019-02-28 10:07 UTC, ivankrut856 commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +    public boolean add(T element) {
А что аннотация?

2019-02-28 10:08 UTC, ivankrut856 commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +    private Comparator<T> comparator = null;
Если вы намекаете, что оно должно extends Comparable<T>, то это же неправда

2019-02-28 10:27 UTC, jzuken commented on myTreeSet/src/test/java/fr/ladybug/team/MyTreeSetTest.java
> +class MyTreeSetTest {
https://github.com/ivankrut856/Java-SPbAU/pull/2#discussion_r256286435
вам не хватило 15 дней, чтобы пройтись по всем задачам и учесть ошибки?

2019-02-28 10:27 UTC, jzuken commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +    public boolean add(T element) {
NotNull

2019-02-28 10:27 UTC, jzuken commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +    private Comparator<T> comparator = null;
нет, я не про extends Comparable

2019-02-28 10:30 UTC, ivankrut856 commented on myTreeSet/src/test/java/fr/ladybug/team/MyTreeSetTest.java
> +class MyTreeSetTest {
Так дедлайн по ним уже прошел к тому времени. Или я могу исправлять до проверки, но после дедлайна?

2019-02-28 23:02 UTC, ivankrut856 commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +    public boolean add(T element) {
Нет, я, конечно, добавлю аннотацию, но я всё ещё считаю, что она делает не то, что нужно

2019-02-28 23:04 UTC, ivankrut856 commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +    public boolean add(T element) {
Я надеюсь, вы потом не скажете, что теперь я бросаю неверное исключение при null...

2019-03-02 06:54 UTC, jzuken commented on myTreeSet/src/test/java/fr/ladybug/team/MyTreeSetTest.java
> +class MyTreeSetTest {
конечно, я же говорил на паре тогда, что когда я рассказываю про замечания, было бы здорово, чтобы вы пошли и поправили их во всех непроверенных решениях. ну иначе правда фигня получается, что за одну ошибку человек несколько раз страдает

2019-03-02 06:54 UTC, jzuken commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +    public boolean add(T element) {
а что она должна делать, и что она делает, по-вашему?

2019-03-02 07:32 UTC, ivankrut856 commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSet.java
> +    public boolean add(T element) {
По мне так она должна указывать программсту, что сюда не должен передаваться null. А делает она ещё какие-то проверки в рантайме, причём только у меня, а на travis, например, она не делает ничего. В любом случае, сейчас я написал так, чтобы и была аннотация и исключение бросалось всегда, поэтому всё норм, кажется

2019-03-13 13:47 UTC, jzuken commented
конфликт с мастером надо бы поправить

2019-03-13 13:53 UTC, jzuken requested changes

2019-03-13 13:53 UTC, jzuken commented on myTreeSet/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
а можно gitignore уже настроить-таки?
-0.5

2019-03-13 13:53 UTC, jzuken commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSetImpl.java
> +            result = ((Comparable<T>)a).compareTo(b);
а можно было проинициализировать компаратор один раз в конструкторе и не делать кучу лишних проверок

2019-03-13 13:53 UTC, jzuken commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSetImpl.java
> +            if ((directionPredicate.test(effectiveResult)) ^ descendingComparison) {
это какая-то жесть нечитаемая совсем. давайте как-нибудь более понятно напишем это

2019-03-13 13:53 UTC, jzuken commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSetImpl.java
> +        private boolean hasNexted = false;
это какое-то синтаксически некорректное имя

2019-03-13 18:42 UTC, ivankrut856 commented on myTreeSet/src/main/java/fr/ladybug/team/MyTreeSetImpl.java
> +            result = ((Comparable<T>)a).compareTo(b);
На паре мы, кажется, вас убедили, что это тоже норм

2019-03-14 20:18 UTC, ivankrut856 commented
> конфликт с мастером надо бы поправить

done

2019-03-20 09:07 UTC, merged