Hw 04
ivankrut856/Java-SPbAU pull request #5
Opened 2019-02-25 22:20 UTC by ivankrut856

2019-03-16 13:08 UTC, jzuken requested changes

2019-03-16 13:08 UTC, jzuken commented on db/src/main/java/fr/ladybug/team/Main.java
> +        Scanner scanner = new Scanner(System.in);
крайне некрасиво запускать программу и показывать пустой экран пользователю. всегда должно быть какое-то приглашение к вводу
-0.5

2019-03-16 13:08 UTC, jzuken commented on db/src/main/java/fr/ladybug/team/Main.java
> +        while(isRunning) {
пробел

2019-03-16 13:08 UTC, jzuken commented on db/src/main/java/fr/ladybug/team/Main.java
> +                    String name = askString(scanner, "Name: ");
оно у меня буферизуется вот так:

1
asd
123
> Name: Phone: Done

2019-03-16 13:08 UTC, jzuken commented on db/src/main/java/fr/ladybug/team/Main.java
> +                    String name = askString(scanner, "Name: ");
полная копипаста с командой 6
-1

2019-03-16 13:08 UTC, jzuken commented on db/src/main/java/fr/ladybug/team/Phonebook.java
> +            throw new NoSuchElementException();
4
aaaaaaa
222222
Exception in thread "main" java.util.NoSuchElementException
	at fr.ladybug.team.Phonebook.removePair(Phonebook.java:196)
	at fr.ladybug.team.Main.main(Main.java:48)

-1

2019-03-16 13:08 UTC, jzuken commented on db/src/main/java/fr/ladybug/team/Phonebook.java
> +            throw new NoSuchElementException();
добавьте, пожалуйста, адекватную обработку всех нестандартных ситуаций

2019-03-16 13:08 UTC, jzuken commented on db/src/main/java/fr/ladybug/team/Phonebook.java
> +        public Name name;
публичных полей в публичных классах не бывает
-0.5

2019-03-16 13:08 UTC, jzuken commented on db/src/main/java/fr/ladybug/team/Phonebook.java
> +    enum NoSuchElementPolicy {
модификатор доступа потерялся

2019-03-16 13:08 UTC, jzuken commented on db/src/test/java/fr/ladybug/team/PhonebookTest.java
> +        phonebook = new Phonebook("phonebook_db");
то есть оно в тестах перетирает рабочую базу? прекрасно.
-0.5

2019-03-17 11:25 UTC, ivankrut856 commented on db/src/main/java/fr/ladybug/team/Main.java
> +        Scanner scanner = new Scanner(System.in);
У меня есть приглашение. В askCommand выводится "> ".

2019-03-19 16:20 UTC, jzuken commented on db/src/main/java/fr/ladybug/team/Main.java
> +        Scanner scanner = new Scanner(System.in);
ну не надо ёрничать

2019-03-19 17:58 UTC, ivankrut856 commented on db/src/main/java/fr/ladybug/team/Main.java
> +        Scanner scanner = new Scanner(System.in);
В любом случае, если вы про какое-то приветствие, то я его добавил. Мне казалось, что "> " -- это как раз приглашение

2019-03-20 09:54 UTC, jzuken commented on db/src/main/java/fr/ladybug/team/Main.java
> +        Scanner scanner = new Scanner(System.in);
ну вот теперь вы знаете, что этого недостаточно :)

2019-03-20 10:54 UTC, jzuken requested changes

2019-03-20 10:54 UTC, jzuken commented on db/src/main/java/fr/ladybug/team/Main.java
> +        System.out.println("Welcome to the world greatest phonebook");
этого всё равно недостаточно. а как понять, что вводить то? на этот вопрос пользователь получает хоть какой-то ответ, только если введёт что-то некорректное, и программа завершится, что принципиально неправильно. а что каждая команда значит, так до сих пор и нигде не узнать

2019-03-20 10:54 UTC, jzuken commented on db/src/main/java/fr/ladybug/team/Main.java
> +                    String name = askString(scanner, "Name: ");
всё ещё не поправлено
-1

2019-03-20 10:54 UTC, jzuken commented on db/src/main/java/fr/ladybug/team/Phonebook.java
> +            throw new NoSuchElementException();
пытаюсь добавить пользователя два раза с одним телефоном, оно молча не делает ничего

2019-03-20 10:59 UTC, ivankrut856 commented on db/src/main/java/fr/ladybug/team/Main.java
> +                    String name = askString(scanner, "Name: ");
Тогда я не понял, о чём речь? У меня flushы везде

2019-03-20 11:25 UTC, jzuken commented on db/src/main/java/fr/ladybug/team/Main.java
> +                    String name = askString(scanner, "Name: ");
ну вот тот пример, что я выше описал, всё ещё ровно так же отображается

2019-03-20 11:31 UTC, ivankrut856 commented on db/src/main/java/fr/ladybug/team/Main.java
> +                    String name = askString(scanner, "Name: ");
А. Ну да, если вы всё одновременно вводите, то он сразу получает три строки и последовательно реагирует. Так же делают все программы. Какой результат вы хотитет увидеть? Я должен как-то понимать по сколько строк за раз вводит пользователь и изменять поведение? Я не понимаю :(

2019-03-20 12:06 UTC, ivankrut856 commented on db/src/main/java/fr/ladybug/team/Main.java
> +                    String name = askString(scanner, "Name: ");
Вы уверены, что мои флаши не помогают? Я поспрашивал у ребят, они говорят, что нужно просто флаши везде поставить. У меня так и есть

2019-03-20 12:17 UTC, ivankrut856 commented on db/src/main/java/fr/ladybug/team/Main.java
> +                    String name = askString(scanner, "Name: ");
Если руками вводить, то всё нормально выводится. Последовательно. Понятное дело, что есть ctrl+v`шыть в консоль этот ввод, то вывод только после него будет

2019-03-21 15:31 UTC, merged