Hw 05
ivankrut856/Java-SPbAU pull request #8
Opened 2019-03-13 18:08 UTC by ivankrut856

2019-03-18 17:23 UTC, jzuken requested changes

2019-03-18 17:23 UTC, jzuken commented on reflector/src/test/java/fr/ladybug/team/ReflectorTest.java
> +    void testIndevDifferences() {
все ваши тесты не работают под виндами. лучше использовать System.lineSeparator(), он кроссплатформенный

2019-03-18 17:23 UTC, jzuken commented on reflector/src/test/java/fr/ladybug/team/IndevTestClass.java
> +public class IndevTestClass<T extends String & Member> {
их бы лучше положить в отдельный пакет

2019-03-18 17:23 UTC, jzuken commented on reflector/src/test/java/fr/ladybug/team/IndevTestClass.java
> +public class IndevTestClass<T extends String & Member> {
и хорошо бы побольше вариантов проверить. абстрактные классы, интерфейсы, иерархии их и т.п.

2019-03-18 17:23 UTC, jzuken commented on reflector/src/main/java/fr/ladybug/team/Reflector.java
> +        int[][] dp = new int[aSize + 1][bSize + 1];
что это за мракобесие? я вроде уже много раз просил не использовать таких имён переменных, ничему вас жизнь не учит
-2

2019-03-18 17:23 UTC, jzuken commented on reflector/src/main/java/fr/ladybug/team/Reflector.java
> +    private static @NotNull ArrayList<Integer> longestCommonSequence(
и вообще зачем вам эта функция такая? нельзя построить множество и взять пересечение что ли?

2019-03-18 17:26 UTC, ivankrut856 commented on reflector/src/main/java/fr/ladybug/team/Reflector.java
> +    private static @NotNull ArrayList<Integer> longestCommonSequence(
Нет, конечно. Смотрите, тогда у 1023 и 123 будет 3 различия, а не 2

2019-03-18 17:26 UTC, ivankrut856 commented on reflector/src/main/java/fr/ladybug/team/Reflector.java
> +        int[][] dp = new int[aSize + 1][bSize + 1];
Кажется, мы обсуждали когда-то, что конвенциальные наименования разрешены...

2019-03-18 17:28 UTC, ivankrut856 commented on reflector/src/test/java/fr/ladybug/team/IndevTestClass.java
> +public class IndevTestClass<T extends String & Member> {
Понял.
Интефейсы, кстати, не надо поддерживать
> В метод printStructure() можно передавать только классы. Enum, интерфейсы, аннотации и т.д. можно не обрабатывать.

2019-03-19 16:23 UTC, jzuken commented on reflector/src/test/java/fr/ladybug/team/IndevTestClass.java
> +public class IndevTestClass<T extends String & Member> {
интерфейсы не требуется передавать в printStructure(), а внутри тестовых классов они то вполне могут использовать

2019-03-19 16:24 UTC, jzuken commented on reflector/src/main/java/fr/ladybug/team/Reflector.java
> +        int[][] dp = new int[aSize + 1][bSize + 1];
не вижу ничего конвенциального в именах dp и par

2019-03-19 16:25 UTC, jzuken commented on reflector/src/main/java/fr/ladybug/team/Reflector.java
> +    private static @NotNull ArrayList<Integer> longestCommonSequence(
значит это слишком сложный и непонятный алгоритм сам по себе

2019-03-19 17:35 UTC, ivankrut856 commented on reflector/src/test/java/fr/ladybug/team/IndevTestClass.java
> +public class IndevTestClass<T extends String & Member> {
> интерфейсы не требуется передавать в printStructure(), а внутри тестовых классов они то вполне могут использоваться
Ну да. Тогда у меня есть один интерфейс в IndevTestClass. Видно, что он хорошо выводится. И это покрывает все случаи, где может встретиться интерфейс так, чтобы вывелся

2019-03-19 17:37 UTC, ivankrut856 commented on reflector/src/main/java/fr/ladybug/team/Reflector.java
> +    private static @NotNull ArrayList<Integer> longestCommonSequence(
Не, ну блин. Я старался сделать так, чтобы моя программа работала нормально, реализовал алгоритм, который более менее классический в этом смысле (НОП, [https://neerc.ifmo.ru/wiki/index.php?title=%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B0_%D0%BE_%D0%BD%D0%B0%D0%B8%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%B5%D0%B9_%D0%BE%D0%B1%D1%89%D0%B5%D0%B9_%D0%BF%D0%BE%D0%B4%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D0%B8](url)). Вы хотите, чтобы я его удалил?

2019-03-19 17:54 UTC, ivankrut856 commented on reflector/src/test/java/fr/ladybug/team/IndevTestClass.java
> +public class IndevTestClass<T extends String & Member> {
Потому что вещи, вложенные на второй уровень уже не выводятся, потому что от вещей на первом уровне остаются только объявления (как требуется в задании)

2019-03-20 09:53 UTC, jzuken commented on reflector/src/test/java/fr/ladybug/team/IndevTestClass.java
> +public class IndevTestClass<T extends String & Member> {
абстрактные классы?

2019-03-20 09:54 UTC, jzuken commented on reflector/src/main/java/fr/ladybug/team/Reflector.java
> +    private static @NotNull ArrayList<Integer> longestCommonSequence(
ну вот я пока не понимаю, зачем вам он тут

2019-03-20 09:56 UTC, ivankrut856 commented on reflector/src/test/java/fr/ladybug/team/IndevTestClass.java
> +public class IndevTestClass<T extends String & Member> {
Ну они тоже есть теперь

2019-03-20 09:58 UTC, ivankrut856 commented on reflector/src/main/java/fr/ladybug/team/Reflector.java
> +    private static @NotNull ArrayList<Integer> longestCommonSequence(
У меня берутся текстовые представления классов и сравниваются.
Допустим у меня в первом классе методы a(), b(), c(), d(), а во втором a(), c(), d(). Если бы я совсем построчно сравнивал (даже с учётом сортировки методов по именам, которая у меня есть), то нашёл бы 3 различия: b() != c(), c() != d(), d() != EMPTY, поэтому я нахожу наибольшую общую подпоследовательность из методов и заключаю, что всё остальное -- различия.

2019-03-20 10:56 UTC, jzuken commented on reflector/src/main/java/fr/ladybug/team/Reflector.java
> +    private static @NotNull ArrayList<Integer> longestCommonSequence(
и почему нельзя положить методы-строки во множества и взять их пересечение, как я в первом комментарии написал?

2019-03-20 10:58 UTC, ivankrut856 commented on reflector/src/main/java/fr/ladybug/team/Reflector.java
> +    private static @NotNull ArrayList<Integer> longestCommonSequence(
Окееей, теоретически можно. Но зачем усложнять? Мне переделать?

2019-03-20 11:11 UTC, ivankrut856 commented on reflector/src/main/java/fr/ladybug/team/Reflector.java
> +    private static @NotNull ArrayList<Integer> longestCommonSequence(
То есть. У меня идёт сплошной текст. Из него нужно сначала вычленить все методы (regex писать?), потом поля, потом всё остальное и потом уже положить всё в какое-то множество и пересечь. Гораздо проще же работать тупо с текстом (типа как diff), поэтому я считаю, что моё решение норм

2019-03-20 11:18 UTC, jzuken commented on reflector/src/main/java/fr/ladybug/team/Reflector.java
> +    private static @NotNull ArrayList<Integer> longestCommonSequence(
вы сейчас серьёзно? вы же сами эти классы в строку преобразовали выше, а теперь её парсите героически. у вас есть объект типа Class, из которого вы можете получить эти списки в явном виде, и работать с ними

2019-03-20 11:22 UTC, ivankrut856 commented on reflector/src/main/java/fr/ladybug/team/Reflector.java
> +    private static @NotNull ArrayList<Integer> longestCommonSequence(
Ну да, а можно воспользоваться уже существующим кодом. Почему вы просто настаиваете на одном конкретном пути решения задачи, а мой вам не нравится? Ну нигде же не написано, что так нельзя или ещё что-нибудь, сейчас нужно будет весь метод переделывать, чтобы сделать абсолютно по-другому

2019-03-20 11:35 UTC, jzuken commented on reflector/src/main/java/fr/ladybug/team/Reflector.java
> +    private static @NotNull ArrayList<Integer> longestCommonSequence(
потому что если можно решить какую-то задачу, не написав лишнего кода, то надо делать именно так. потому что мой вариант не вовлекает написание какого-то страшного и непонятного кода, в котором легко ошибиться и который сложно сопровождать. ни один адекватный тимлид такой код в свой репозиторий бы не принял. 

это сугубо моё субъективное профессиональное мнение, разумеется, но пока что вам не удаётся привести ни одного убедительного аргумента в пользу своего решения, поэтому я всё ещё на нём настаиваю.

2019-03-21 19:52 UTC, merged

2019-03-21 19:52 UTC, jzuken commented
алгоритм вы так и не переделали, поэтому ещё снимаю балл

2019-03-21 19:53 UTC, ivankrut856 commented
> алгоритм вы так и не переделали, поэтому ещё снимаю балл

Фух, всего балл, не так плохо, как я думал