Thread pool
ivankrut856/Java-SPbAU pull request #9
Opened 2019-04-29 22:43 UTC by ivankrut856

2019-05-02 12:33 UTC, jzuken requested changes

2019-05-02 12:33 UTC, jzuken commented on threadPool/.gradle/buildOutputCleanup/cache.properties
> +#Thu Apr 25 23:37:35 MSK 2019
бинарники гредла выкладывать не надо, только враппер
-0.5

2019-05-02 12:33 UTC, jzuken commented on threadPool/src/main/java/fr/ladybug/team/lightfuture/LightFuture.java
> +    void interrupted();
от метода с таким названием логично было бы ожидать возвращения булевого значения

2019-05-02 12:33 UTC, jzuken commented on threadPool/src/main/java/fr/ladybug/team/lightfuture/FreeFuture.java
> + * {@inheritDoc}
не, если вы пишете какое-то описание, то inheritDoc уже не работает. сгенерируйте себе доки и посмотрите

2019-05-02 12:33 UTC, jzuken commented on threadPool/src/main/java/fr/ladybug/team/lightfuture/FreeFuture.java
> +        return task;
unchecked assignment

2019-05-02 12:33 UTC, jzuken commented on threadPool/src/main/java/fr/ladybug/team/lightfuture/FreeFuture.java
> +        var task = new FreeFuture<>(action, executor);
а тут переменная ни к чему

2019-05-02 12:33 UTC, jzuken commented on threadPool/src/main/java/fr/ladybug/team/lightfuture/FreeFuture.java
> +    public synchronized boolean isReady() {
а почему эта штука synchronized, а submit, например, нет7

2019-05-02 12:33 UTC, jzuken commented on threadPool/src/main/java/fr/ladybug/team/ThreadPool.java
> +                thread.interrupt();
join ещё бы не помешал

2019-05-02 17:21 UTC, ivankrut856 commented on threadPool/src/main/java/fr/ladybug/team/lightfuture/FreeFuture.java
> +        return task;
У меня в IDEA это указано в качестве Error, поэтому у меня бы не скомпилилось даже. Вы уверены, что там где-то Unchecked assignment?

2019-05-02 17:28 UTC, ivankrut856 commented on threadPool/src/main/java/fr/ladybug/team/ThreadPool.java
> +                thread.interrupt();
Вы уверены? В Java же нет гарантии, что потоки завершатся через interrupt, поэтому есть шанс, что вызывающий поток зависнет. Ну да ладно

2019-05-02 19:15 UTC, jzuken commented on threadPool/src/main/java/fr/ladybug/team/ThreadPool.java
> +                thread.interrupt();
ну значит и ваша штука зависнет, нормально надо потоки реализовывать. а сейчас толку от вашего shutdown'а мало

2019-05-02 19:17 UTC, jzuken commented on threadPool/src/main/java/fr/ladybug/team/lightfuture/FreeFuture.java
> +        return task;
![image](https://user-images.githubusercontent.com/705678/57100617-17631680-6d28-11e9-9cfa-fdcfe4de60e7.png)

2019-05-02 19:40 UTC, ivankrut856 commented on threadPool/src/main/java/fr/ladybug/team/lightfuture/FreeFuture.java
> +        return task;
Причину понял. Очень странно, что у меня не показывается. Интересно, могут ли быть версии IDEA разные

2019-05-03 15:11 UTC, jzuken commented on threadPool/src/main/java/fr/ladybug/team/lightfuture/FreeFuture.java
> +        return task;
у меня 2019.1.1

2019-05-11 09:24 UTC, merged